# Generated by Django 2.2.4 on 2020-03-01 08:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_lineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='county',
        ),
        migrations.AlterField(
            model_name='charge',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
