# Generated by Django 2.2.4 on 2020-02-13 13:56

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_auto_20200213_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, verbose_name='Upload Product Image'),
        ),
    ]
