# Generated by Django 2.2.4 on 2020-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_auto_20200214_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0, verbose_name='Describe the honey flavour'),
            preserve_default=False,
        ),
    ]
